default_language_version:
    python: python3.10
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
-   repo: local
    hooks:
    -   id: black
        name: black
        entry: black
        language: system
        types: [ python ]
-   repo: local
    hooks:
      - id: isort
        name: isort (python)
        entry: isort
        language: system
        types: [ python ]
-   repo: local
    hooks:
      - id: pylint
        name: pylint [mandatory]
        entry: pylint
        language: system
        types: [python]
        args:
          [
            "--disable=missing-function-docstring,missing-module-docstring,missing-class-docstring",
            "-rn", # Only display messages
            "-sn", # Don't display the score
          ]
        verbose: true
-   repo: local
    hooks:
      - id: pylint
        name: pylint [full]
        entry: pylint
        language: system
        types: [python]
        args:
          [
            "--exit-zero"
          ]
        verbose: true
-   repo: https://github.com/python-poetry/poetry
    rev: 1.2.2
    hooks:
      - id: poetry-check
      - id: poetry-lock
