version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  jobs:
    post_create_environment:
      - echo "Command run at 'post_create_environment' step"
      - python -m pip install --upgrade --no-cache-dir pip setuptools
      - pip install poetry
      - poetry install
      - pip install -e .

sphinx:
  builder: html
  fail_on_warning: false

formats:
  - pdf
  - epub
