version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  jobs:
    pre_create_environment:
      - echo "Command run at 'pre_create_environment' step"
      - pip install poetry
      - poetry install
    post_build:
      - echo "Command run at 'post_build' step"
      - echo `date`
