name: winter-env
channels:
  - conda-forge
  - http://astroconda.gemini.edu/public
  - http://ssb.stsci.edu/astroconda
  - defaults
dependencies:
  - astromatic-scamp
  - astromatic-source-extractor
  - astromatic-swarp
  - pip=22.2.1
  - python=3.10.5
  - python_abi=3.10=2_cp310
  - pip:
    - appnope==0.1.2
    - argon2-cffi==21.1.0
    - astroplan==0.8
    - astropy==5.0.4
    - astroquery==0.4.6
    - attrs==21.2.0
    - avro==1.11.0
    - avro-python3==1.10.2
    - backcall==0.2.0
    - beautifulsoup4==4.10.0
    - bleach==4.1.0
    - cffi==1.15.0
    - charset-normalizer==2.0.7
    - confluent-kafka==1.9.0
    - cycler==0.11.0
    - debugpy==1.5.1
    - decorator==5.1.0
    - defusedxml==0.7.1
    - docker==5.0.3
    - entrypoints==0.3
    - ephem==4.1.3
    - fastavro==1.5.2
    - fonttools==4.28.1
    - html5lib==1.1
    - idna==3.3
    - importlib-metadata==4.8.2
    - iniconfig==1.1.1
    - ipykernel==6.5.1
    - ipython==7.29.0
    - ipython-genutils==0.2.0
    - ipywidgets==7.6.5
    - jedi==0.18.1
    - jinja2==3.0.3
    - jsonschema==4.2.1
    - jupyter==1.0.0
    - jupyter-client==7.0.6
    - jupyter-console==6.4.0
    - jupyter-core==4.9.1
    - jupyterlab-pygments==0.1.2
    - jupyterlab-widgets==1.0.2
    - keyring==23.2.1
    - kiwisolver==1.3.2
    - markupsafe==2.0.1
    - matplotlib==3.5.2
    - matplotlib-inline==0.1.3
    - mimeparse==0.1.3
    - mistune==0.8.4
    - nbclient==0.5.9
    - nbconvert==6.3.0
    - nbformat==5.1.3
    - nest-asyncio==1.5.1
    - notebook==6.4.6
    - numpy==1.22.4
    - packaging==21.3
    - pandas==1.4.3
    - pandocfilters==1.5.0
    - parso==0.8.2
    - penquins==2.1.0
    - pexpect==4.8.0
    - photutils==1.5.0
    - pickleshare==0.7.5
    - pillow==8.4.0
    - pluggy==1.0.0
    - prometheus-client==0.12.0
    - prompt-toolkit==3.0.22
    - psycopg==3.0.15
    - psycopg-binary==3.0.15
    - psycopg2==2.9.3
    - ptyprocess==0.7.0
    - py==1.11.0
    - pycparser==2.21
    - pyerfa==2.0.0.1
    - pyfftw==0.13.0
    - pygments==2.10.0
    - pymongo==4.1.1
    - pyparsing==3.0.6
    - pyrsistent==0.18.0
    - pytest==7.1.2
    - python-dateutil==2.8.2
    - pytz==2021.3
    - pyvo==1.1
    - pyyaml==6.0
    - pyzmq==22.3.0
    - qtconsole==5.2.0
    - qtpy==1.11.2
    - requests==2.26.0
    - scipy==1.8.0
    - send2trash==1.8.0
    - setuptools==60.9.3
    - setuptools-scm==6.3.2
    - six==1.16.0
    - soupsieve==2.3.1
    - terminado==0.12.1
    - testpath==0.5.0
    - tomli==1.2.2
    - tornado==6.1
    - tqdm==4.64.0
    - traitlets==5.1.1
    - urllib3==1.26.7
    - wcwidth==0.2.5
    - webencodings==0.5.1
    - websocket-client==1.2.3
    - wget==3.2
    - wheel==0.37.0
    - widgetsnbextension==3.5.2
    - zipp==3.6.0