[tool.poetry]
name = "winterdrp"
version = "0.6.0"
description = "Modular open-source astronomy image reduction framework"
authors = ["Robert Stein <rdstein@caltech.edu>", "Viraj Karambelkar <viraj@astro.caltech.edu>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10.0,<3.12"
astroplan = "^0.8"
astropy = {extras = ["all"], version = "^5.2.1"}
astroquery = "^0.4.6"
avro-python3 = "~1.10.1"
coveralls = {extras = ["toml"], version = "^3.3.1"}
confluent-kafka = "^2.0.2"
docker = "^6.0.1"
ephem = "^4.1.3"
fastavro = "^1.7.1"
jupyter = "^1.0.0"
matplotlib = "^3.6.3"
lacosmic = "^1.0.0"
numpy = "~1.23.5"
pandas = "^1.5.3"
penquins = "^2.2.0"
photutils = "^1.6.0"
psycopg = {extras = ["binary"], version = "^3.1.8"}
pydl = {version = "^1.0.0rc1", allow-prereleases = true}
pyFFTW = "^0.13.1"
setuptools = "^67.0.0"
watchdog = "^2.2.1"
wget = "^3.2"
toml = "^0.10.2"
sphinx-mdinclude = "^0.5.3"
black = "^23.1.0"
pre-commit = "^3.0.2"
isort = {extras = ["pyproject"], version = "^5.12.0"}
pylint = "^2.15.10"
mypy = "^0.991"
types-requests = "^2.28.11.8"
types-toml = "^0.10.8.1"
pandas-stubs = "^1.5.3.230203"
autopep8 = "^2.0.0"

[tool.poetry.group.docs.dependencies]
sphinx = "^5.3.0"

[tool.coverage.run]
source = ["winterdrp"]
concurrency = ["thread"]
omit = ["winterdrp/__main__.py", "winterdrp/processors/send_to_fritz.py"]

[tool.coverage.report]
# Regexes for lines to exclude from consideration
exclude_lines = [
    # Have to re-enable the standard pragma
    "pragma: no cover",
    # Don't complain about missing debug-only code:
    "def __repr__",
    # Don't complain if tests don't hit defensive assertion code:
    "raise AssertionError",
    "raise NotImplementedError",
    "raise KeyError",
    "except KeyError",
    "raise ValueError",
    "except JSONDecodeError:",
    "raise requests.exceptions.RequestException",
    # Don't complain if non-runnable code isn't run:
    "if 0:",
    "if False:",
    'if __name__ == "__main__":',
    "err =",
    "logger.error",
    "raise"
    ]
ignore_errors = true

[tool.isort]
profile = "black"

[tool.pylint.format]
max-line-length = "88"
disable=["logging-fstring-interpolation"]
good-names=["i", "j", "k", "ex", "Run", "_", "ra", "pa", "x", "y", "nx", "ny", "dx", "dy", "df", "t0", "t1"]

[build-system]
requires = ["setuptools", "wheel", "poetry-core>=1.2.0",]
build-backend = "poetry.core.masonry.api"
