"""
Module for generating custom processors and catalogues for WINTER
"""
from mirar.pipelines.winter.generator.astrometry import winter_astrometric_ref_catalog_generator
from mirar.pipelines.winter.generator.astrometry import winter_astrometry_sextractor_catalog_purifier
from mirar.pipelines.winter.generator.candidates import winter_candidate_annotator_filterer
from mirar.pipelines.winter.generator.candidates import winter_candidate_avro_fields_calculator
from mirar.pipelines.winter.generator.candidates import winter_candidate_quality_filterer
from mirar.pipelines.winter.generator.candidates import winter_new_source_updater
from mirar.pipelines.winter.generator.candidates import winter_skyportal_annotator
from mirar.pipelines.winter.generator.candidates import winter_source_entry_updater
from mirar.pipelines.winter.generator.photometry import winter_astrostat_catalog_purifier
from mirar.pipelines.winter.generator.photometry import winter_photcal_color_columns_generator
from mirar.pipelines.winter.generator.photometry import winter_photometric_catalog_generator
from mirar.pipelines.winter.generator.photometry import winter_photometric_catalogs_purifier
from mirar.pipelines.winter.generator.photometry import winter_ref_photometric_catalogs_purifier
from mirar.pipelines.winter.generator.photometry import winter_reference_phot_calibrator
from mirar.pipelines.winter.generator.realbogus import apply_rb_to_table
from mirar.pipelines.winter.generator.reduce import mask_stamps_around_bright_stars
from mirar.pipelines.winter.generator.reduce import select_winter_dome_flats_images
from mirar.pipelines.winter.generator.reduce import select_winter_flat_images
from mirar.pipelines.winter.generator.reduce import select_winter_sky_flat_images
from mirar.pipelines.winter.generator.reduce import winter_anet_sextractor_config_path_generator
from mirar.pipelines.winter.generator.reduce import winter_boardid_6_demasker
from mirar.pipelines.winter.generator.reduce import winter_fourier_filtered_image_generator
from mirar.pipelines.winter.generator.reduce import winter_history_deprecated_constraint
from mirar.pipelines.winter.generator.reduce import winter_imsub_catalog_purifier
from mirar.pipelines.winter.generator.reduce import winter_stackid_annotator
from mirar.pipelines.winter.generator.references import winter_astrometric_ref_catalog_namer
from mirar.pipelines.winter.generator.references import winter_photometric_ref_catalog_namer
from mirar.pipelines.winter.generator.references import winter_reference_generator
from mirar.pipelines.winter.generator.references import winter_reference_image_resampler_for_zogy
from mirar.pipelines.winter.generator.references import winter_reference_psf_phot_sextractor
from mirar.pipelines.winter.generator.references import winter_reference_psfex
from mirar.pipelines.winter.generator.references import winter_reference_sextractor
from mirar.pipelines.winter.generator.references import winter_reference_stack_annotator
from mirar.pipelines.winter.generator.references import winter_wfau_component_image_stacker
